language: go

services:
  - docker

go:
  - "1.10"

env:
  - CGO_ENABLED=0

script:
  - go vet
  - go test
  - go build -ldflags "-s -w -X main.build=$TRAVIS_BUILD_NUMBER -X main.rev=$TRAVIS_COMMIT" -a -tags netgo
  - docker build -t "nytimes/drone-gae:$TRAVIS_BRANCH" .
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" != "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push "nytimes/drone-gae:$TRAVIS_BRANCH";
    fi
